spring:
  application:
    name: admin-earn-back
  datasource:
    url: jdbc:h2:C:\h2\db
    username: sa
    password : test
  h2:
    console:
      enabled: true
mybatis:
  type-aliases-package: com.sk.eadmin.biz.dto
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
